apiVersion: v1
kind: ConfigMap
metadata:
  name: kasm-values
  namespace: kasm
data:
  values.yaml: |
    # Configuración adicional si es necesaria
    # La mayoría de la configuración está en el helm-release.yaml base

