apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /pocket-id/jellyfin/client_id
    - secretKey: client_secret
      remoteRef:
        key: /pocket-id/jellyfin/client_secret
    - secretKey: cookie_secret
      remoteRef:
        key: /oauth2-proxy/jellyfin/cookie_secret
    - secretKey: oidc_issuer_url
      remoteRef:
        key: /pocket-id/jellyfin/oidc_issuer_url

