apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding
  - ddns-updater
  - jellyfin
  - n8n
  - memos
  # - ollama
  # - redlib  # Disabled: Reddit is blocking OAuth client creation
  - dbgate
